/** Run BEFORE changing a published generator. Existing daily files are never overwritten. */
import { generate, KINDS } from "../src/puzzles.ts";
import { dailyDifficulty, DIFFICULTIES, supportsDifficulty } from "../src/difficulty.ts";

const through = Deno.args[0];
if (
  !/^\d{4}-\d{2}-\d{2}$/.test(through ?? "") ||
  new Date(`${through}T12:00:00Z`).toISOString().slice(0, 10) !== through || through < "2026-09-01"
) {
  throw new Error("Usage: deno task archive YYYY-MM-DD (last date to preserve)");
}
const directory = new URL("../src/archive/", import.meta.url);
await Deno.mkdir(directory, { recursive: true });
const revision = new TextDecoder().decode(
  (await new Deno.Command("git", {
    args: ["rev-parse", "HEAD"],
    stdout: "piped",
  }).output()).stdout,
).trim();
let checkedSource = false;
const dates: string[] = [];
for (let time = Date.UTC(2026, 8, 1);; time += 86400000) {
  const date = new Date(time).toISOString().slice(0, 10);
  if (date > through) break;
  dates.push(date);
  const path = new URL(`${date}.json`, directory);
  try {
    await Deno.stat(path);
    continue;
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
  if (!checkedSource) {
    const clean = await new Deno.Command("git", {
      args: ["diff", "--quiet", "HEAD", "--", "src", ":(exclude)src/archive"],
    }).output();
    if (!clean.success) {
      throw new Error("Archive before editing source; restore the published revision first.");
    }
    checkedSource = true;
  }
  const puzzles: Record<string, ReturnType<typeof generate>> = {};
  const defaults: Record<string, string | null> = {};
  for (const kind of KINDS) {
    defaults[kind] = dailyDifficulty(kind, date) ?? null;
    for (const level of [undefined, ...(supportsDifficulty(kind) ? DIFFICULTIES : [])]) {
      puzzles[`${kind}/${level ?? "classic"}`] = generate(kind, date, level);
    }
  }
  await Deno.writeTextFile(
    path,
    JSON.stringify({ schema: 1, date, revision, defaults, puzzles }) + "\n",
    { createNew: true },
  );
  console.log(`Archived ${date}: ${Object.keys(puzzles).length} boards`);
}
// Retain later snapshots if the command is rerun with an earlier end date.
for await (const file of Deno.readDir(directory)) {
  if (/^\d{4}-\d{2}-\d{2}\.json$/.test(file.name) && !dates.includes(file.name.slice(0, 10))) {
    dates.push(file.name.slice(0, 10));
  }
}
dates.sort();
await Deno.writeTextFile(
  new URL("index.ts", directory),
  "// Generated by scripts/archive-puzzles.ts. Fixed data, no historical generators.\n" +
    dates.map((date, i) => `import day${i} from "./${date}.json" with { type: "json" };`).join(
      "\n",
    ) +
    `\nexport default [${dates.map((_, i) => `day${i}`).join(", ")}];\n`,
);
