/** Run BEFORE changing a published generator. Existing boards are never overwritten. */
import { generate, KINDS } from "../src/puzzles.ts";
import { dailyDifficulty, DIFFICULTIES, supportsDifficulty } from "../src/difficulty.ts";

const through = Deno.args[0];
if (
  !/^\d{4}-\d{2}-\d{2}$/.test(through ?? "") ||
  new Date(`${through}T12:00:00Z`).toISOString().slice(0, 10) !== through || through < "2026-09-01"
) {
  throw new Error("Usage: deno task archive YYYY-MM-DD (last date to preserve)");
}
const directory = new URL("../src/archive/", import.meta.url);
await Deno.mkdir(directory, { recursive: true });
const revision = new TextDecoder().decode(
  (await new Deno.Command("git", {
    args: ["rev-parse", "HEAD"],
    stdout: "piped",
  }).output()).stdout,
).trim();
let checkedSource = false;
async function requirePublishedSource() {
  if (checkedSource) return;
  const clean = await new Deno.Command("git", {
    args: ["diff", "--quiet", "HEAD", "--", "src", ":(exclude)src/archive"],
  }).output();
  if (!clean.success) {
    throw new Error("Archive before editing source; restore the published revision first.");
  }
  checkedSource = true;
}
// New difficulties can ship after a date's original snapshot was frozen.
// Preserve these alternatives separately, leaving existing daily files untouched.
const alternativesPath = new URL("alternatives.json", directory);
let alternatives: { schema: number; revision: string; puzzles: Record<string, ReturnType<typeof generate>> } =
  { schema: 1, revision, puzzles: {} };
try {
  alternatives = JSON.parse(await Deno.readTextFile(alternativesPath));
  if (alternatives.schema !== 1 || !alternatives.puzzles) throw new Error("Unsupported alternatives archive");
} catch (error) {
  if (!(error instanceof Deno.errors.NotFound)) throw error;
}
let addedAlternatives = 0;
const dates: string[] = [];
for (let time = Date.UTC(2026, 8, 1);; time += 86400000) {
  const date = new Date(time).toISOString().slice(0, 10);
  if (date > through) break;
  dates.push(date);
  const path = new URL(`${date}.json`, directory);
  try {
    const day = JSON.parse(await Deno.readTextFile(path));
    for (const kind of KINDS.filter(supportsDifficulty)) {
      for (const level of DIFFICULTIES) {
        const key = `${date}/${kind}/${level}`;
        if (day.puzzles[`${kind}/${level}`] || alternatives.puzzles[key]) continue;
        await requirePublishedSource();
        alternatives.puzzles[key] = generate(kind, date, level);
        addedAlternatives++;
      }
    }
    continue;
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
  await requirePublishedSource();
  const puzzles: Record<string, ReturnType<typeof generate>> = {};
  const defaults: Record<string, string | null> = {};
  for (const kind of KINDS) {
    defaults[kind] = dailyDifficulty(kind, date) ?? null;
    for (const level of [undefined, ...(supportsDifficulty(kind) ? DIFFICULTIES : [])]) {
      puzzles[`${kind}/${level ?? "classic"}`] = generate(kind, date, level);
    }
  }
  await Deno.writeTextFile(
    path,
    JSON.stringify({ schema: 1, date, revision, defaults, puzzles }) + "\n",
    { createNew: true },
  );
  console.log(`Archived ${date}: ${Object.keys(puzzles).length} boards`);
}
if (addedAlternatives) {
  alternatives.revision = revision;
  await Deno.writeTextFile(alternativesPath, JSON.stringify(alternatives) + "\n");
  console.log(`Archived ${addedAlternatives} additional published difficulty boards`);
}
// Retain later snapshots if the command is rerun with an earlier end date.
for await (const file of Deno.readDir(directory)) {
  if (/^\d{4}-\d{2}-\d{2}\.json$/.test(file.name) && !dates.includes(file.name.slice(0, 10))) {
    dates.push(file.name.slice(0, 10));
  }
}
dates.sort();
await Deno.writeTextFile(
  new URL("index.ts", directory),
  "// Generated by scripts/archive-puzzles.ts. Fixed data, no historical generators.\n" +
    dates.map((date, i) => `import day${i} from "./${date}.json" with { type: "json" };`).join(
      "\n",
    ) +
    `\nexport default [${dates.map((_, i) => `day${i}`).join(", ")}];\n`,
);
